# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/connector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend/connector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61\x63kend/connector.proto\x12\x07netwalk\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n\x0fMeasurementData\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04imsi\x18\x02 \x01(\t\x12\x0c\n\x04imei\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0clocation_lat\x18\x05 \x01(\x01\x12\x14\n\x0clocation_lon\x18\x06 \x01(\x01\x12\x0c\n\x04rsrp\x18\x07 \x01(\x05\x12\x0c\n\x04sinr\x18\x08 \x01(\x05\x12\x14\n\x0cnetwork_type\x18\t \x01(\t\x12\x0f\n\x07\x63\x65ll_id\x18\n \x01(\t\x12\x15\n\rbattery_level\x18\x0b \x01(\x05\x12\x16\n\x0eprocessor_temp\x18\x0c \x01(\x01\x12\x12\n\nos_version\x18\r \x01(\t\x12\x17\n\x0fthroughput_mbps\x18\x0e \x01(\x01\x12\x33\n\x0ftest_start_time\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rtest_end_time\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"0\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2X\n\x12MeasurementService\x12\x42\n\x0fSaveMeasurement\x12\x18.netwalk.MeasurementData\x1a\x15.netwalk.SaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.connector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASUREMENTDATA']._serialized_start=70
  _globals['_MEASUREMENTDATA']._serialized_end=489
  _globals['_SAVERESPONSE']._serialized_start=491
  _globals['_SAVERESPONSE']._serialized_end=539
  _globals['_MEASUREMENTSERVICE']._serialized_start=541
  _globals['_MEASUREMENTSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
