user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream iperf_tcp_backends {
        hash $remote_addr; # should enforce ip sticky-ness

        server netwalk-iperf:5201;
        server netwalk-iperf-2:5201;
        server netwalk-iperf-3:5201;
    }

    upstream iperf_udp_backends {
        hash $remote_addr;

        server netwalk-iperf:5201;
        server netwalk-iperf-2:5201;
        server netwalk-iperf-3:5201;
    }

    server {
        listen 5201;
        proxy_pass iperf_tcp_backends;
        proxy_timeout 10m; # session keep-alive timeout
    }

    server {
        listen 5201 udp;
        proxy_pass iperf_udp_backends;
        proxy_timeout 10m;
    }
}
