name: Android Release Build

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: androidApp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build debug apk
        run: ./gradlew :app:clean assembleDebug

      - name: Rename apk
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/NetWalk-debug.apk

      - name: Find APK
        id: apk
        run: echo "path=app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: androidApp/${{ steps.apk.outputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
